// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZhdy7Rw3jffipxsDvvz7_C_b4teVg1k',
    appId: '1:893074789710:android:e932bc88da6665b3c4ba1f',
    messagingSenderId: '893074789710',
    projectId: 'fondexuzb',
    databaseURL: 'https://fondexuzb-default-rtdb.firebaseio.com',
    storageBucket: 'fondexuzb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Khoz4y93GCj3mOPi2FoluDipplH1av0',
    appId: '1:893074789710:ios:13bf2fb0c1d52496c4ba1f',
    messagingSenderId: '893074789710',
    projectId: 'fondexuzb',
    databaseURL: 'https://fondexuzb-default-rtdb.firebaseio.com',
    storageBucket: 'fondexuzb.firebasestorage.app',
    androidClientId: '893074789710-0l3vbjo032et95r50si36cd0339lstpq.apps.googleusercontent.com',
    iosClientId: '893074789710-eg41gl4g2pqk6003jumvj9umudnh6f62.apps.googleusercontent.com',
    iosBundleId: 'felix.fondex.uz',
  );

}