name: driver
description: "A new Flutter project."
publish_to: 'none' 
version: 1.2.16+42

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  country_code_picker: ^3.4.1
  firebase_app_check: ^0.4.1+2
  crypto: ^3.0.7

  dotted_border: ^3.1.0
  http: ^1.6.0
  googleapis_auth: ^2.0.0
  firebase_database: ^12.1.0

  cached_network_image: ^3.4.1
  flutter_easyloading: ^3.0.5
  flutter_email_sender: ^8.0.0
  flutter_html: any
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.2.3
  location: ^8.0.1
  get: ^4.7.3
  google_maps_flutter: ^2.14.0
  cloud_functions: ^6.0.4
  latlong2: ^0.9.1

  image_picker: ^1.2.1
  intl: ^0.20.2
  pin_code_fields: ^8.0.1

  provider: ^6.1.5+1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_datepicker: ^31.2.15
  timer_count_down: ^2.2.2
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  date_picker_timeline: ^1.2.7
  flutter_rating_bar: ^4.0.1
  flutter_polyline_points: ^3.1.0
  clipboard: ^2.0.2
  map_launcher: ^4.4.2
  timelines_plus: ^1.0.8
  in_app_review: ^2.0.11
  share_plus: ^12.0.1
  package_info_plus: ^9.0.0
  mailer: ^6.6.0
  webview_flutter: ^4.9.0
  webview_flutter_wkwebview: ^3.23.0
  photo_view: ^0.15.0
  path_provider: ^2.1.5
  path: ^1.9.1
  video_compress: ^3.1.4
  video_player: ^2.10.1
  audioplayers: ^6.5.1
  flutter_callkit_incoming: ^2.5.0
  flutter_background_service: ^5.1.0



  geolocator: ^14.0.2
  yandex_mapkit: ^4.2.1

dependency_overrides:
  http: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

  fonts:
    - family: Urbanist-Black
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf

    - family: Urbanist-Bold
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf

    - family: Urbanist-ExtraBold
      fonts:
        - asset: assets/fonts/Urbanist-ExtraBold.ttf

    - family: Urbanist-ExtraLight
      fonts:
        - asset: assets/fonts/Urbanist-ExtraLight.ttf

    - family: Urbanist-Light
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf

    - family: Urbanist-Medium
      fonts:
        - asset: assets/fonts/Urbanist-Medium.ttf

    - family: Urbanist-Regular
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf

    - family: Urbanist-SemiBold
      fonts:
        - asset: assets/fonts/Urbanist-SemiBold.ttf

    - family: Urbanist-Thin
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf

  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/audio/
    - assets/
